version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  computer_vision:
    build: ../computer_vision_api
    volumes:
      - ../computer_vision_api/models:/code/models
    ports:
      - "8000:8000"

    entrypoint: uvicorn app.main:app --host 0.0.0.0 --port 8000


volumes:
  db:
    driver: local